notifications:
  slack: vqlabs:j71yKGBW4ipmLoWcJuteN83i

cache:
  directories:
    - node_modules

addons:
  sauce_connect: true

language: node_js

node_js:
  - "9"

matrix:
  include:
  - name: "simple-bitcoin-wallet"
    sudo: false
    install:
    - npm install

    script:
    - npm run build
    - npm run test
