cache:
  directories:
    - node_modules

addons:
  sauce_connect: true

language: node_js

node_js:
  - "11"

matrix:
  include:
  - name: "simple-bitcoin-wallet"
    sudo: false

    install:
    - npm install

    script:
    - npm run build
    - npm run test
